Refactoring
antoniomcoelho/Daradata-assignment-1 pull request #2
Opened 2023-02-27 15:59 UTC by antoniomcoelho

2023-02-28 15:12 UTC, MrCordeiro requested changes
Me gusta so far! I suggested a few alternatives on how to extract the values.

2023-02-28 15:12 UTC, MrCordeiro commented on life_expectancy/cleaning.py
> +    filtered_df['value'] = filtered_df['value'].astype(float)
In general, I try to avoid list comprehensions in pandas. This is because you lose the power of vectorization that pandas gets from numpy. You can use regex to filter all the digits and then convert them to floats in 2 lines:

```python
filtered_df['value'].replace(r'^\D+', '', regex=True, inplace=True)
filtered_df['value'] = filtered_df['value'].astype(float)
```

If you don't want to use regex, you can use apply instead. Something, like this:

```python
def _extract_numeric_value(row):
    value = row['value']
    if str(value)[0].isdigit():
        return float(value.split(" ")[0])
    else:
        return None

filtered_df['value'] = filtered_df.apply(_extract_numeric_value, axis=1)
filtered_df.dropna(inplace=True)
```

It _is_ less performant though. It's a tradeoff between performance and readability.

2023-02-28 20:48 UTC, anaritarc commented on life_expectancy/cleaning.py
> +    ''' Load data '''
Since the function in itself already explains its goals, aka, to clean the data,I believe this comment is not needed.

2023-02-28 21:00 UTC, anaritarc requested changes

2023-02-28 21:00 UTC, anaritarc commented on life_expectancy/cleaning.py
> +    # Filter per region
I also believe this comment is not necessary, is very clear in your code that you are filtering the region

2023-02-28 21:00 UTC, anaritarc commented on life_expectancy/cleaning.py
> +    ''' Load data '''
Since the function in itself already explains its goals, aka, to clean the data,I believe this comment is not needed.

2023-02-28 21:00 UTC, anaritarc commented on life_expectancy/cleaning.py
> +    #REGION_USER = add_region_user()
I believe we usually should avoid commenting code, but I don't know if there is an underlying reason to have this here.

2023-03-02 16:12 UTC, antoniomcoelho commented on life_expectancy/cleaning.py
> +    filtered_df['value'] = filtered_df['value'].astype(float)
Fiz alterações.

2023-03-03 09:13 UTC, MrCordeiro approved these changes

2023-03-06 18:38 UTC, anaritarc approved these changes

2023-03-19 14:00 UTC, merged