Assigment3
antoniomcoelho/Daradata-assignment-1 pull request #3
Opened 2023-03-29 13:54 UTC by antoniomcoelho

2023-03-30 12:11 UTC, anaritarc commented on life_expectancy/tests/test_load_save.py
> +    with mock.patch.object(save_data_expected, "to_csv") as to_csv_mock:
this is awesome :star-struck:

2023-03-30 12:21 UTC, anaritarc requested changes

2023-03-30 12:21 UTC, anaritarc commented on life_expectancy/tests/test_load_save.py
> +from life_expectancy.cleaning import clean_data
clean_data is not used here, I would remove it 😄

2023-03-30 12:21 UTC, anaritarc commented on life_expectancy/tests/test_load_save.py
> +from . import INIT_DIR, FIXTURES_DIR, OUTPUT_DIR
you have called init_dir but it isn't used, I would also remove it

2023-03-30 12:21 UTC, anaritarc commented on life_expectancy/tests/test_load_save.py
> +    #load_data_expected = pd.read_csv( FIXTURES_DIR / "eu_life_expectancy_raw.tsv", sep="\t")
Also I had the recommendation to also use patch in the load data, I believe you could also try it ❓

2023-03-30 15:32 UTC, MrCordeiro requested changes

2023-03-30 15:32 UTC, MrCordeiro commented on life_expectancy/load_save.py
> +from pathlib import Path # pylint: disable=import-error
```suggestion
from pathlib import Path
```

Algum outra cena pode estar a causar este import error

2023-03-30 15:32 UTC, MrCordeiro commented on life_expectancy/load_save.py
> +import argparse
Validar se não apareceu um "unused-import"

2023-03-30 15:32 UTC, MrCordeiro commented on life_expectancy/pipeline.py
> +def add_region_user():
```suggestion
def _add_region_user() -> str:
```

2023-03-30 15:32 UTC, MrCordeiro commented on life_expectancy/tests/__init__.py
> +INIT_DIR = Path(__file__).parent.parent
Validar se está a ser utilizado (nome generico)

2023-03-30 15:32 UTC, MrCordeiro commented on life_expectancy/tests/conftest.py
> +    #file_path.unlink(missing_ok=True)
Deeeeeelete

2023-03-30 15:32 UTC, MrCordeiro commented on life_expectancy/tests/test_load_save.py
> +
```suggestion
from unittest.mock import patch


@patch("life_expectancy.load_save.pd.read_table")
def test_load_data(mock_load, load_data_expected):
    """Run the `load_data` function and compare the output to the expected output"""
    
    mock_load.return_value = "INSERT FIXTURE"

```

2023-03-30 15:32 UTC, MrCordeiro commented on life_expectancy/tests/test_load_save.py
> +        to_csv_mock.assert_called_with(OUTPUT_DIR / "pt_life_expectancy.csv", index=False)
É uma maneira bué boa!

2023-03-30 15:32 UTC, MrCordeiro commented on life_expectancy/tests/test_load_save.py
> +        save_data(save_data_expected)
```
        to_csv_mock.side_effect = print("I'm being saved!!)
```

2023-04-17 14:51 UTC, antoniomcoelho reviewed
All changes done.

2023-04-18 09:14 UTC, anaritarc approved these changes
Awesome Antonio 💪🏼 🥳

2023-04-18 11:29 UTC, MrCordeiro requested changes
There were 2 comments that were marked as resolved, but that I couldn't find what changed.

The `test_load_data` is consuming data from the `data` directory, which we don't want (as it's our "database" in the context of this exercise)
Instead, you should patch the method that is doing the saving and replace it with a fixture.

2023-04-18 11:29 UTC, MrCordeiro commented on life_expectancy/tests/test_load_save.py
> +
I don't see any changes here. Why is it marked as resolved?

2023-04-18 11:29 UTC, MrCordeiro commented on life_expectancy/tests/test_load_save.py
> +    )
This comment is a complement to the previous one.

2023-04-18 15:32 UTC, anaritarc commented on life_expectancy/tests/test_load_save.py
> +
my bad sorry @MrCordeiro

2023-04-18 15:41 UTC, MrCordeiro commented on life_expectancy/tests/test_load_save.py
> +
Wait... haha...did you mark it as resolved, @anaritarc ?

2023-04-23 09:31 UTC, anaritarc commented on life_expectancy/tests/test_load_save.py
> +
I did :) I though it was done 🙈

2023-05-04 15:11 UTC, MrCordeiro approved these changes

2023-05-16 13:54 UTC, merged