Assigment4
antoniomcoelho/Daradata-assignment-1 pull request #4
Opened 2023-05-17 20:08 UTC by antoniomcoelho

Assigment 4 - first version

2023-05-18 08:28 UTC, MrCordeiro requested changes
Just made two initial comments. But I believe @anaritarc should review it first. Why haven't you added her to the PR?

2023-05-18 08:28 UTC, MrCordeiro commented on life_expectancy/cleaning.py
Your pipeline is failing because you removed this file without altering your workflow to reflect that.

PS: I also noticed you aren't installing the local life_expectancy package when running your workflow.

2023-05-18 08:28 UTC, MrCordeiro commented on life_expectancy/pipeline.py
> +from clean_files import *
It's generally recommended to avoid wildcard imports for a couple of reasons:

-  Clarity: people won't know from where a particular function or attribute is coming from 
- Name Clashes: Wildcard imports could potentially overwrite existing names without notice, which can lead to bugs that are difficult to track down.

2023-05-21 21:28 UTC, anaritarc commented on life_expectancy/tests/test_clean_files.py
> +import unittest.mock as mock  # pylint: disable=consider-using-from-import
I also made this :) you made two imports for mock, this one

2023-05-21 21:28 UTC, anaritarc commented on life_expectancy/tests/test_clean_files.py
> +from unittest.mock import patch
and this one, you only need one

2023-05-21 21:28 UTC, anaritarc commented on life_expectancy/clean_files.py
> +            filtered_df = df_first_column[df_first_column['country'].isin([region])].copy()
I am not sure, but I don't think you need the .copy() here

2023-05-21 21:28 UTC, anaritarc commented on life_expectancy/clean_files.py
> +    def list_countries():
could this be a @staticmethod?

2023-05-21 21:28 UTC, anaritarc commented on life_expectancy/clean_files.py
> +from enum import Enum, unique, Flag
you have imported the Flag but didn't saw being used anywhere

2023-05-21 21:28 UTC, anaritarc commented on life_expectancy/clean_files.py
> +DATA_DIR = Path(__file__).parent / 'data'
nice 🤩

2023-05-21 21:28 UTC, anaritarc commented on life_expectancy/clean_files.py
> +class dataFormatsStrategy(ABC):
For class is recommended to[ 'Start each word with a capital letter.'](https://realpython.com/python-pep8/#naming-styles)

2023-05-21 21:28 UTC, anaritarc commented on life_expectancy/clean_files.py
> +class cleanFile:
For class is recommended to[ 'Start each word with a capital letter.'](https://realpython.com/python-pep8/#naming-styles)

2023-05-22 08:29 UTC, MrCordeiro commented on life_expectancy/clean_files.py
> +    def list_countries():
Or a classmethod. Then you replace `for country in cls: ` below

2023-05-22 09:14 UTC, antoniomcoelho commented on life_expectancy/pipeline.py
> +from clean_files import *
Changed.

2023-05-22 09:27 UTC, antoniomcoelho commented on life_expectancy/clean_files.py
> +DATA_DIR = Path(__file__).parent / 'data'
Thanks! :)

2023-05-22 10:05 UTC, antoniomcoelho commented on life_expectancy/cleaning.py
I don't know how to do this.

2023-05-22 13:52 UTC, MrCordeiro reviewed
See if that helps, Antonio

2023-05-22 13:52 UTC, MrCordeiro commented on .github/workflows/python-package.yml
>          python -m pip install pylint pytest pandas
To install the package locally:

```suggestion
        python -m pip install pylint pytest
        pip install .
```

This also takes care of installing the package dependencies

2023-05-22 13:52 UTC, MrCordeiro commented on .github/workflows/python-package.yml
> +        $(git ls-files '*.py')
```suggestion
        pylint life_expectancy/
```

`$(git ls-files '*.py')` just lists the python files is won't actually run the linter. Running `pylint` + the name of your package should do the trick.

2023-05-23 10:48 UTC, antoniomcoelho commented on .github/workflows/python-package.yml
>          python -m pip install pylint pytest pandas
Yes, it worked. Thank you!

2023-05-23 11:06 UTC, antoniomcoelho commented on .github/workflows/python-package.yml
> +        $(git ls-files '*.py')
I know, it was lack of attention. :)

2023-05-23 15:20 UTC, anaritarc approved these changes
Não quero fica sozinha no pod, mas fizeste tudo não posso pedir mais nada 😭ainda tenho a Ana Neves, tenho de ser rápida

2023-05-25 11:32 UTC, merged